version: '3'

networks:
  api_viacep:
    driver: bridge

services:
  app:
    container_name: "api_viacep"
    build:
      args:
        user: user
        uid: 1002
      context: .
    image: api-viacep
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    expose:
      - 9223
    networks:
      - api_viacep

  nginx:
    container_name: "api_viacep_nginx"
    image: nginx:alpine
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    ports:
      - "8100:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - api_viacep
